### ISSUE TITLE
Provide utilities to manage nonce in common

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/go-conflux-sdk#110]
When a service interact with blockchain in a single thread, it may send transaction in high TPS, and need to manage the nonce off-chain. SDK could provide a tool (like java SDK) to for developers to manage nonce in common.

**Comment by wangdayong228** [comment]
There are two ways for getting nonce, one is `client.GetNextNonce` to obtain transaction count of executed and another is `RpcTxpoolClient.NextNonce` to obtain transaction count including txpool.
