### ISSUE TITLE
Allow user to call in batch

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/go-conflux-sdk#111]
DAPP usually call contract multiple times to get different data to display on UI page, it is really time consuming, especially the network is bad.

Currently, SDK provide a way for batch RPC requests. However, it is type unsafe and user need to specify method name and arguments. Instead, SDK could provide a new RPC, e.g. `multicall` to read data from one or more contracts in a batch (with one network roundtrip).

Note, **Parity** already has such helpful API (`parity_call`), conflux SDK could just follow the way.

By the way, it's better to implement such function in all other SDKs.

**Comment by wangdayong228** [comment]
implement in pr #124
