### ISSUE TITLE
SDK should provide constructor to get Address from ecdsa.PublicKey or geth common.Address

### ISSUE THREAD

**Issue by wanliqun** [Conflux-Chain/go-conflux-sdk#116]
Conflux address is special with prefix header as followings:
a. builtin address with first 4 bits as 0000;
b. account address with first 4 bits as 0001;
c. contract address with first 4 bits as 1000.

These rules are very obscure for conflux beginners from ethereum background. It would be much better for sdk to provide some encapsulated helper functions to construct conflux address from standard ecdsa.PublicKey struct or geth common.Address.

**Comment by wangdayong228** [comment]
please reference `addressutil.EtherAddressToCfxAddress` and `addressutil.PubkeyToAddress`
