### ISSUE TITLE
RpcPosClient should implement RpcPos interface

### ISSUE THREAD

**Issue by wanliqun** [Conflux-Chain/go-conflux-sdk#123]
type RpcPos interface {
	GetAccount(address postypes.Address, view ...hexutil.Uint64) (postypes.Account, error)
....
}

// GetAccount returns account info at block
func (c *RpcPosClient) GetAccount(address postypes.Address, blockNumber ...uint64) (account postypes.Account, err error) {
	_view := get1stU64Ify(blockNumber)
	err = c.core.CallRPC(&account, "pos_getAccount", address, _view)
	return
}

----------
eg., RpcPosClient GetAccount method parameter doesn't match with RpcPos interface method.

**Comment by wangdayong228** [comment]
solved in #137
