### ISSUE TITLE
context.WaitPacked()  报错！

### ISSUE THREAD

**Issue by doxulovezh** [Conflux-Chain/go-conflux-sdk#129]
1.0.16 context.WaitPacked()  报错！  没有context了！！  exmple 也没有了

**Comment by wangdayong228** [comment]
> 1.0.16 context.WaitPacked() 报错！ 没有context了！！

有详细报错信息吗？

> exmple 也没有了

example 移到 [conflux-fans](https://github.com/conflux-fans/go-conflux-sdk-examples)下 了
