### ISSUE TITLE
contract.Call(nil, res, "NFT_INDEX")   测试网快，正式网极慢！！！call主网合约有BUG！

### ISSUE THREAD

**Issue by doxulovezh** [Conflux-Chain/go-conflux-sdk#133]
合约读取函数不需要签名，只需要节点返回数据即可。同一套代码，测试网快只要1秒，主网特别慢要20秒才返回数据。
测试网RPC:https://test.confluxrpc.com
主网RPC:https://main.confluxrpc.com
但是我使用ConfluxStudio  IDE    RPC同样是https://main.confluxrpc.com，但是确非常快也是1秒级的。

**Comment by doxulovezh** [comment]
我使用conflux-js-sdk编写了一个主网合约call速度非常快<1秒。主网RPC用的是一样的:https://main.confluxrpc.com

**Comment by wangdayong228** [comment]
可以提供demo吗？
