### ISSUE TITLE
use sdk no err, but tx exec fail

### ISSUE THREAD

**Issue by llifezou** [Conflux-Chain/go-conflux-sdk#23]
There is no error using the SDK, but the transaction will fail to execute on the chain. can use conflux studio, the same contract

sdk：
&{TransactionHash:0xfba5d4c56f5ad877caf9442db02e1f960b46e38bc7ba623ecc2776779a1f30b7 Index:0x0 BlockHash:0x911dac0cb7d7ef148b1254727d6d2da6106e95ab10a550ad46462fb6ee24b358 EpochNumber:0x2adbc From:0x1810c2146baeead54c3ee81c95c5486812e0633b To:0x8489db6cbe3df2e8f06432e41df51b6b186dc6dc GasUsed:0x5ede GasFee:0x161686672c00 ContractCreated:<nil> Logs:[] LogsBloom:0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 StateRoot:0x766926eba2dd79e5decfb2788f622d80123f3fcbe90b597893053a014bc1977b OutcomeStatus:0x1}--- 

conflux studio：

&{TransactionHash:0x0cfc6a7ba9b4a8a6029543277c4247bb8ebe33d9a3d8272b956a0c7d2d0dd766 Index:0x0 BlockHash:0xc780a4ebf9b43cb5250eab221e01ad989a0544b74b48fa81dce3482b8929b1e5 EpochNumber:0x2aec6 From:0x1f67cac74ca2d9c56e72b697b4359f84466789e9 To:0x8489db6cbe3df2e8f06432e41df51b6b186dc6dc GasUsed:0x8586 GasFee:0x47868c0 ContractCreated:<nil> Logs:[{Address:0x8489db6cbe3df2e8f06432e41df51b6b186dc6dc Topics:[0x80709b356cf7979327229c81a01a85952dbf0130ae0b10f0faf8b7a6d0ded6dc] Data:0x0000000000000000000000000000000000000000000000000000000000000010}] LogsBloom:0x00000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000 StateRoot:0xe3a2d808ada9131886bbafedd3893d1a37bb3e76a84ae4e1013c4d6d60d1af86 OutcomeStatus:0x0}

**Comment by wangdayong228** [comment]
The first tx has no data field, did it miss?
