### ISSUE TITLE
contract.ABI.Unpack call failed. Wrong mistmatch parameters

### ISSUE THREAD

**Issue by yakamarcher** [Conflux-Chain/go-conflux-sdk#42]
contract.go line number 101 failed
must be 	_, err = contract.ABI.Unpack(method, bytes)
instead of err = contract.ABI.Unpack(resultPtr, method, bytes)

**Comment by wangdayong228** [comment]
Could you print the detail error message? What's your ABI, and please list your code, thank you.

**Comment by wangdayong228** [comment]
That's because your project doesn't use go module, the go-ethereum version which is dependencied by go-conflux-sdk not match correctly. Please use go module to manager your library dependency.
