### ISSUE TITLE
Need utilities for unit conversion

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/go-conflux-sdk#62]
At least following conversion required:
1. CFX <-> Drip
2. CFX <-> Gdrip
3. Grip <-> Drip

By the way, SDK could also provide API to display values with proper unit, e.g. "9.35 CFX", "20 Gdrip". On the other hand, SDK could also provide API to parse value from a string like "20 cfx"

**Comment by wangdayong228** [comment]
support in pr #152
