### ISSUE TITLE
Need utilities to send txs in batch

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/go-conflux-sdk#64]
Now, SDK support to send RPC requests in batch. However, it is not convenient to send transactions in batch. For a dapp/tool, I hope SDK to provide a utility to send transactions in batch much easier.

E.g. 
1. Transfer CFX: user only need to specify `to` and `value`. (`gas` and `storage` are optional)
2. Transfer ERC20 token: user only need to specify `contract address`, `recipient` and `amount`. (`gas` and `storage` are optional)
3. General tx: user only need to specify `to`, `gas`, `storage`, `value` and `data`.
4. APIs to `Send` or `Execute` transactions in batch.

**Comment by wangdayong228** [comment]
implement by bulk caller and bulk sender, reference to #124
