### ISSUE TITLE
New requirements for Client interface

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/go-conflux-sdk#73]
Following APIs is preferred in client interface, which is initialized when creating the client instance:
1. MustGetNetworkID() uint32
2. MustGetChainID() uint
3. WaitForNonceUpdate(target)？// The same with the existing WaitForReceit

**Comment by wangdayong228** [comment]
`Client.GetNetworkIDCached` and `Client.GetNetworkIDCached` are supported.
What does the `target` of `WaitForNonceUpdate(target)` mean

**Comment by boqiu** [comment]
> `Client.GetNetworkIDCached` and `Client.GetNetworkIDCached` are supported. What does the `target` of `WaitForNonceUpdate(target)` mean

Just ignore it, `WaitForReceipt` is enough.
