### ISSUE TITLE
GetEpochReceipts hangs for large size bytes response

### ISSUE THREAD

**Issue by wanliqun** [Conflux-Chain/go-conflux-sdk#74]
sdk.Client GetEpochReceipts hangs @ epoch 12963064. 

with curl, it's ok to response, but the response is very large(~ 7Mb):
` curl -X POST --data '{"jsonrpc":"2.0","method":"cfx_getEpochReceipts","params":["0xC5CCF8"],"id":1}' -H "Content-Type: application/json" http://172.31.124.31`

**Comment by Thegaram** [comment]
What do you suggest? Given that the response might be very large, should we add some kind of paging to this RPC API? @boqiu @wanliqun

**Comment by wanliqun** [comment]
Since cfx_getEpochReceipts is a local rpc, the client and node are usually in the same intranet. I think the response too large might be acceptable for the moment, maybe we can do some compressing?

**Comment by Thegaram** [comment]
We will implement that if this becomes an issue. For now, I suggest we fix this on the SDK side first.

**Comment by Thegaram** [comment]
fyi this should be addressed in the next release of conflux-rust.
